### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by franbuzz** [prototypeninja/quiz-symfony#1]
/src/Controller/QuestionController.php#L20

y a un problème dans le scoring

**Comment by prototypeninja** [comment]
bonsoir,
oui effectivement mais je l'ai déjà corrigé depuis un moment. veuillez
prendre la dernière version du dépot git
https://github.com/prototypeninja/quiz-symfony.git
Merci

**Comment by franbuzz** [comment]
il y a toujours un bug

**Comment by franbuzz** [comment]
![image](https://user-images.githubusercontent.com/46752681/84812243-62181e80-b00e-11ea-92c9-23945c59e2bb.png)

**Comment by prototypeninja** [comment]
Ok. Merci. Je vais vérifier tout de suite.  Je vous tiendrai au courant des
que ces corrigé

**Comment by prototypeninja** [comment]
Bonsoir, je viens de corriger le problème. merci pour vos remarques.

**Comment by franbuzz** [comment]
cool, bravo

**Comment by prototypeninja** [comment]
êtes vous développeur so-buzz?
